name: Run training logic
on:
  schedule:
    - cron: '13 10 * * *'
  push:
    branches:
      - main
      - trial
    paths-ignore:
      - 'README.md'
permissions:
  contents: write
jobs:
  # Data sets to build
  # all:
  #   uses: ./.github/workflows/trainer.yml
  #   with:
  #     edit-set-name: all
  #     train-set-ids: '[]'
  #     bayes-set-ids: '[]'
  #     trial-set-ids: '[]'
  #
  # reported:
  #   uses: ./.github/workflows/trainer.yml
  #   with:
  #     edit-set-name: reported
  #     train-set-ids: '[1, 2]'
  #     bayes-set-ids: '[]'
  #     trial-set-ids: '[]'
  #
  # original-c:
  #   uses: ./.github/workflows/trainer.yml
  #   with:
  #     edit-set-name: original-c
  #     train-set-ids: '[7]'
  #     bayes-set-ids: '[]'
  #     trial-set-ids: '[8]'
  #
  # original-d:
  #   uses: ./.github/workflows/trainer.yml
  #   with:
  #     edit-set-name: original-d
  #     train-set-ids: '[9]'
  #     trial-set-ids: '[10]'
  #     bayes-set-ids: '[11]'
  #
  # original-testing-c:
  #   uses: ./.github/workflows/trainer.yml
  #   with:
  #     edit-set-name: original-testing-c
  #     train-set-ids: '[13]'
  #     trial-set-ids: '[14]'
  #     bayes-set-ids: '[]'
  #
  # original-testing-d:
  #   uses: ./.github/workflows/trainer.yml
  #   with:
  #     edit-set-name: original-testing-d
  #     train-set-ids: '[15]'
  #     trial-set-ids: '[16]'
  #     bayes-set-ids: '[17]'
  #
  # original-testing-auto:
  #   uses: ./.github/workflows/trainer.yml
  #   with:
  #     edit-set-name: original-testing-auto
  #     train-set-ids: '[19]'
  #     trial-set-ids: '[20]'
  #     bayes-set-ids: '[]'
  #
  # original-testing-triplet:
  #   uses: ./.github/workflows/trainer.yml
  #   with:
  #     edit-set-name: original-testing-triplet
  #     train-set-ids: '[21]'
  #     trial-set-ids: '[22]'
  #     bayes-set-ids: '[23]'
  #
  # random-edits:
  #   uses: ./.github/workflows/trainer.yml
  #   with:
  #     edit-set-name: random-edits
  #     train-set-ids: '[25]'
  #     trial-set-ids: '[26]'
  #     bayes-set-ids: '[]'
  #
  # very-large:
  #   uses: ./.github/workflows/trainer.yml
  #   with:
  #     edit-set-name: very-large
  #     train-set-ids: '[28]'
  #     trial-set-ids: '[29]'
  #     bayes-set-ids: '[30]'

  test:
    uses: ./.github/workflows/trainer.yml
    with:
      edit-set-name: test
      train-set-ids: '[2]'
      trial-set-ids: '[]'
      bayes-set-ids: '[]'

  # Reporting of completed datasets
  release:
    uses: ./.github/workflows/releaser.yml
    needs:
      - test
      # - all
      # - reported
      # - original-c
      # - original-d
      # - original-testing-c
      # - original-testing-d
      # - original-testing-auto
      # - original-testing-triplet
      # - random-edits
      # - very-large
