name: Run training logic
on:
  schedule:
    - cron: '13 10 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
permissions:
  contents: write
jobs:
  # Generic pre warming of the API endpoint
  pre-warm:
    runs-on: ubuntu-20.04
    steps:
      - run: curl https://cluebotng-review.toolforge.org/api/export/trainer.json > /dev/null

  # Data sets to build
  all:
    uses: ./.github/workflows/trainer.yml
    needs: [pre-warm]
    with:
      edit-set-name: all
      edit-set-ids: '[]'

  reported:
    uses: ./.github/workflows/trainer.yml
    needs: [pre-warm]
    with:
      edit-set-name: reported
      edit-set-ids: '[1, 2]'

  original-c:
    uses: ./.github/workflows/trainer.yml
    needs: [pre-warm]
    with:
      edit-set-name: original-c
      edit-set-ids: '[7]'

  original-d:
    uses: ./.github/workflows/trainer.yml
    needs: [pre-warm]
    with:
      edit-set-name: original-d
      edit-set-ids: '[9]'

  original-testing-c:
    uses: ./.github/workflows/trainer.yml
    needs: [pre-warm]
    with:
      edit-set-name: original-testing-c
      edit-set-ids: '[13]'

  original-testing-d:
    uses: ./.github/workflows/trainer.yml
    needs: [pre-warm]
    with:
      edit-set-name: original-testing-d
      edit-set-ids: '[15]'

  original-testing-auto:
    uses: ./.github/workflows/trainer.yml
    needs: [pre-warm]
    with:
      edit-set-name: original-testing-auto
      edit-set-ids: '[19]'

  original-testing-triplet:
    uses: ./.github/workflows/trainer.yml
    needs: [pre-warm]
    with:
      edit-set-name: original-testing-triplet
      edit-set-ids: '[21]'

  random-edits:
    uses: ./.github/workflows/trainer.yml
    needs: [pre-warm]
    with:
      edit-set-name: random-edits
      edit-set-ids: '[25]'

  very-large:
    uses: ./.github/workflows/trainer.yml
    needs: [pre-warm]
    with:
      edit-set-name: very-large
      edit-set-ids: '[28]'

  # Reporting of completed datasets
  release:
    uses: ./.github/workflows/releaser.yml
    needs:
      - all
      - reported
      - original-c
      - original-d
      - original-testing-c
      - original-testing-d
      - original-testing-auto
      - original-testing-triplet
      - random-edits
      - very-large
