name: Dataset trainer

on:
  workflow_call:
    inputs:
      edit-set-name:
        required: true
        type: string
      edit-set-ids:
        required: true
        type: string

jobs:
  trainer:
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with: { python-version: '3.9' }
      - name: Install cbng-trainer
        run: pip install git+https://github.com/cluebotng/trainer.git@main
      - name: Download reviewed edits
        run: |
          [ ! -z "${{ join(fromJSON(inputs.edit-set-ids)) }}" ] && export filter="--edit-set ${{ join(fromJSON(inputs.edit-set-ids), ' --edit-set ') }}"
          cbng-trainer download-edits --output=edits.xml $filter
      - name: Build databases
        run: |
          mkdir -p "results/"
          cbng-trainer build-database --input=edits.xml --output "results/"
      - name: Prepare files
        run: |
          sudo chown -R runner:docker "results/"
          sudo find results -type f -exec chmod 644 {} \;
          cp edits.xml "results/" || true
      - name: Compare databases
        run: |
          cbng-trainer compare-database --target "results/" --output "results/" || true

          # Cleanup before we upload
          rm -f results/Dockerfile
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.edit-set-name }}
          path: results/*
