name: Run training logic
on:
  schedule:
    - cron: '13 10 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
permissions:
  contents: write
jobs:
  # Data sets to build
  all:
    uses: ./.github/workflows/trainer.yml
    with:
      edit-set-name: all
      train-set-ids: '[]'
      bayes-set-ids: '[]'
      trial-set-ids: '[]'

  reported:
    uses: ./.github/workflows/trainer.yml
    with:
      edit-set-name: reported
      train-set-ids: '[1, 2]'
      bayes-set-ids: '[]'
      trial-set-ids: '[]'

  original-c:
    uses: ./.github/workflows/trainer.yml
    with:
      edit-set-name: original-c
      train-set-ids: '[7]'
      bayes-set-ids: '[]'
      trial-set-ids: '[8]'

  original-d:
    uses: ./.github/workflows/trainer.yml
    with:
      edit-set-name: original-d
      train-set-ids: '[9]'
      trial-set-ids: '[10]'
      bayes-set-ids: '[11]'

  original-testing-c:
    uses: ./.github/workflows/trainer.yml
    with:
      edit-set-name: original-testing-c
      train-set-ids: '[13]'
      trial-set-ids: '[14]'
      bayes-set-ids: '[]'

  original-testing-d:
    uses: ./.github/workflows/trainer.yml
    with:
      edit-set-name: original-testing-d
      train-set-ids: '[15]'
      trial-set-ids: '[16]'
      bayes-set-ids: '[17]'

  original-testing-auto:
    uses: ./.github/workflows/trainer.yml
    with:
      edit-set-name: original-testing-auto
      train-set-ids: '[19]'
      trial-set-ids: '[20]'
      bayes-set-ids: '[]'

  original-testing-triplet:
    uses: ./.github/workflows/trainer.yml
    with:
      edit-set-name: original-testing-triplet
      train-set-ids: '[21]'
      trial-set-ids: '[22]'
      bayes-set-ids: '[23]'

  random-edits:
    uses: ./.github/workflows/trainer.yml
    with:
      edit-set-name: random-edits
      train-set-ids: '[25]'
      trial-set-ids: '[26]'
      bayes-set-ids: '[]'

  very-large:
    uses: ./.github/workflows/trainer.yml
    with:
      edit-set-name: very-large
      train-set-ids: '[28]'
      trial-set-ids: '[29]'
      bayes-set-ids: '[30]'

  # Reporting of completed datasets
  update_readme:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with: { python-version: '3.9' }
      - name: Update README
        run: |
          pip install requests
          ./.github/scripts/update-readme.py

          git config user.email "worker@github"
          git config user.name "Github Actions"

          git add README.md
          git commit -m 'Update README'
          git push origin ${GITHUB_REF##*/}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs:
      - all
      - reported
      - original-c
      - original-d
      - original-testing-c
      - original-testing-d
      - original-testing-auto
      - original-testing-triplet
      - random-edits
      - very-large
